#!/bin/bash

set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.zshrc" "$HOME/.zshrc"

mkdir -p "$HOME/.local/bin"
ln -sfn "$PWD/scripts" "$HOME/.local/bin/scripts"

for i in vim git tmux termux; do
  cd $i && ./setup
  cd - &>/dev/null
done
