#!/usr/bin/env bash

function confirm {
  printf "Set up %-12s [Y/n]: " "${1}?"
  read conf
  [[ ! ${conf,,} =~ ^n ]]
}


ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.bashrc" "$HOME/.zshrc"

ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -sf "$PWD/.profile" "$HOME/.zprofile"

mkdir -p "$HOME/.local/bin"
ln -sfn "$PWD/scripts" "$HOME/.local/bin/scripts"


auto=(
  alacritty
  distrobox
  git
  vim
  termux # skips itself if not in a termux session
  tmux
)

optional=(
)


for i in ${auto[@]}; do
  echo "Setting up ${i}"
  ${i}/setup
done

for i in ${optional[@]}; do
  if confirm "${i}"; then
    ${i}/setup
  fi
done
