#!/usr/bin/env bash

if type konsole &>/dev/null; then
  mkdir -p "$HOME/.local/share/konsole/shortcuts"

  cp konsolerc "$HOME/.config/konsolerc"
  
  ln -sf "$PWD/main.profile" "$HOME/.local/share/konsole/main.profile"
  ln -sf "$PWD/AdaptaNokto.colorscheme" "$HOME/.local/share/konsole/AdaptaNokto.colorscheme"
  ln -sf "$PWD/shortcuts" "$HOME/.local/share/konsole/shortcuts/shortcuts"
fi
