#!/usr/bin/env bash

if [ ! -z ${WAYLAND_DISPLAY} ]; then
  wl-copy >/dev/null 2>&1
elif [ ! -z ${WSL_DISTRO_NAME} ]; then
  /mnt/c/Windows/System32/clip.exe >/dev/null 2>&1
else
  xclip -selection c >/dev/null 2>&1
fi

