#!/bin/sh

filename="$1"
parent="$(dirname "$filename")"

if [ -d "$filename" ]; then
  echo "$(cd "$filename" && pwd -P)"
elif [ -d "$parent" ]; then
  echo "$(cd "$parent" && pwd -P)/$(basename "$filename")"
fi
