#!/usr/bin/env bash

shopt -s nullglob

ENABLEDIR="${HOME}/.config/containers/systemd"


main() {
  if [ $# -lt 1 ]; then
    usage
    exit
  fi

  case "$1" in
    e|enable)
      shift
      enable "$@"
      ;;
    d|disable)
      shift
      disable "$@"
      ;;
    s|status)
      status
      ;;
    r|reload)
      reload
      ;;
    start)
      shift
      start "$@"
      ;;
    stop)
      shift
      stop "$@"
      ;;
    setup)
      setup
      ;;
    dryrun)
      shift
      dryrun "$@"
      ;;
    h|help|-h|--help)
      usage
      ;;
    *)
      echo "Unknown command '$1'"
      usage
      exit 1
      ;;
  esac
}


usage() {
  echo 'quad COMMAND [service(s)]'
  echo 'Manages podman quadlet files'
  echo
  echo 'Commands:'
  echo '  e, enable    symlinks unit files into ~/.config/containers/systemd'
  echo '  d, disable   removes existing symlinks'
  echo '  s, status    print symlink state and podman status'
  echo '  r, reload    does a user daemon-reload to regenerate systemd files'
  echo '  start        starts [service] via systemctl'
  echo '  stop         stops [service] via systemctl'
  echo '  dryrun       runs quadlet -dryrun -user to parse files'
  echo '  setup        initial setup, creates folder structure'
}


enable() {
  local file target
  for file in "$@"; do
    target="$(readlink -f "$file")"
    echo "Enabling $file"
    ln -sf "${target}" "${ENABLEDIR}/${file}"
  done
  reload
}


disable() {
  local file
  for file in "$@"; do
    echo "Disabling $file"
    unlink "${ENABLEDIR}/${file}"
  done
  reload
}


status() {
  local pod_status file ctrname servicename status
  pod_status="$(podman ps -a --format '[{{.Names}}]={{.State}}')"
  printf '%-30s %-30s %s\n' "LINK" "TARGET" "PODMAN STATUS"
  for file in "${ENABLEDIR}"/*.container; do
    ctrname=$(basename -s .container "$file")
    servicename="$(awk -F= '/^ContainerName=/ {name = $2} END {print name}' "$file")"
    servicename="${servicename:-"systemd-${ctrname}"}"
    servicename="${servicename//\%N/"${ctrname}"}"
    status="$(awk -F= "/\[$servicename\]/ {print \$2}" <<< "$pod_status")"
    printf '%-30s %-30s %s\n' "$(basename "$file")" "$(basename "$(readlink -f "$file")")" "${status:--}"
  done
}


reload() {
  echo "Reloading..."
  systemctl --user daemon-reload
}


start() {
  systemctl --user start "$@"
}


stop() {
  systemctl --user stop "$@"
}


setup() {
  echo 'Creating folder: '
  echo "  ${ENABLEDIR}"
  mkdir -p "${ENABLEDIR}"
}

dryrun() {
  if [ $# -eq 1 ]; then
    # only print section between the ---*.service--- separators
    /usr/libexec/podman/quadlet -dryrun -user \
      |awk "/---$1.service---/"'{flag=1;print;next}/---.*.service---/{flag=0}flag'
  else
    # print all
    /usr/libexec/podman/quadlet -dryrun -user
  fi \
    2> >(sed $'s,.*,\e[34m&\e[m,' 1>&2) \
    |sed $'s!---.*.service---!\e[01;32m&\e[0m!g'
    # colorize stderr and ---*.service--- titles
}


main "$@"