#!/bin/bash

SECRETS_DIR="$HOME/.secrets"

##### COMPLETION
if [[ -n "$COMP_LINE" ]]; then
  IFS=" " read -ra cl <<< "$COMP_LINE"
  if [[ -f "$SECRETS_DIR/$3" ]]; then
    compgen -W "$(sed -n "s/\(^.*\)=\".*\"/\1/p" "$SECRETS_DIR/$3")" "$2"
    exit
  fi
  [[ ${#cl[@]} -gt 2 ]] && exit
  compgen -W "$(ls "$SECRETS_DIR")" "$2"
  exit
fi

[[ -n "$1" && -n "$2" ]] && printf '%s' "$(sed -n "s/^$2=\"\(.*\)\"/\1/p" "$SECRETS_DIR/$1")"
