#!/bin/bash

SECRETS_DIR="$HOME/.secrets"

##### COMPLETION
if [[ -n "$COMP_LINE" ]]; then
  cl=($COMP_LINE)
  [[ ${#cl[@]} > 2 ]] && exit
  if [[ -f "$SECRETS_DIR/$3" ]]; then
    compgen -W "$(sed -n "s/\(^.*\)=\".*\"/\1/p" "$SECRETS_DIR/$3")" $2
  else
    compgen -W "$(ls $SECRETS_DIR)" $2
  fi
  exit
fi

[[ -n "$1" && -n "$2" ]] && printf '%s' "$(sed -n "s/^$2=\"\(.*\)\"/\1/p" "$SECRETS_DIR/$1")"
