#!/bin/sh

CHAT_ID="$(secret telegramsend DEFAULT_CHAT_ID)"
BOT_TOKEN="$(secret telegramsend BOT_TOKEN)"

if [ -n "$2" ]; then
  CHAT_ID="$1"
  shift
fi

MESSAGE="$1"

curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
     -H 'Content-Type: application/json' \
     --data '{"chat_id":"'"$CHAT_ID"'", "parse_mode":"Markdown", "text":"'"$MESSAGE"'"}' > /dev/null 2>&1

exit $?
