#!/usr/bin/env bash

# run as $USER in container
arr=("$@")
for i in "${!arr[@]}"; do
    if [[ ${arr[$i]} == *"root:root"* ]]; then
        arr[$i]="$(echo "${arr[$i]}" | sed "s|root:root|$USER:$USER|g")"
    fi
done

# check if running in flatpak or not
if [ -z ${container+x} ]; then
  exec podman "${arr[@]}"
else
  exec flatpak-spawn --host podman "${arr[@]}"
fi
