#!/bin/sh
# base16-gruvbox-hard for TTYs

[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P01d2021
                 \e]P1fb4934
                 \e]P2b8bb26
                 \e]P3fabd2f
                 \e]P483a598
                 \e]P5d3869b
                 \e]P68ec07c
                 \e]P7d5d5d5
                 \e]P8666666
                 \e]P9fb4934
                 \e]PAb8bb26
                 \e]PBfabd2f
                 \e]PC83a598
                 \e]PDd3869b
                 \e]PE8ec07c
                 \e]PFe5e5e5
                 \ec'
